#!/bin/bash
export MTOOLSRC=mtoolsrc
export MTOOLS_NO_VFAT=1
mkdir -p diskimgs/

# Create source package
tar -c --exclude-vcs --exclude-vcs-ignores --no-acls --no-selinux --no-xattrs --old-archive --exclude=.vs --exclude=.idea --exclude=binaries --exclude=projects/compdb --exclude=diskimgs -f diskimgs/src.tar.Z .

# For MS-DOS, use Watcom 11 output
dd if=/dev/zero of=fssetter.img bs=512 count=1440 status=none
mformat -f 720 -v FSSETTER a:
mcopy -sv binaries/dos/watcom11/fssetter.exe a:
mv fssetter.img diskimgs/dos.img

# Create 5.25" MS-DOS floppy image
dd if=/dev/zero of=fssetter.img bs=512 count=720 status=none
mformat -f 360 -v FSSETTER a:
mcopy -sv binaries/dos/watcom11/fssetter.exe a:
mv fssetter.img diskimgs/dos525.img

# Create 3.5" DD floppy image for classic Amiga
dd if=/dev/zero of=fssetter.img bs=512 count=1440 status=none
mformat -f 720 -v FSSETTER a:
mcopy -sv binaries/amigaos/fssetter a:
mv fssetter.img diskimgs/amiga.img

# Create 3.5" HD floppy image for PowerPC Amiga
dd if=/dev/zero of=fssetter.img bs=512 count=2880 status=none
mformat -f 1440 -v FSSETTER a:
mcopy -sv binaries/amigaos binaries/amigaos4 binaries/morphos a:
mv fssetter.img diskimgs/amigappc.img

# For 16-bit OS/2 use Watcom 11
dd if=/dev/zero of=fssetter.img bs=512 count=1440 status=none
mformat -f 720 -v FSSETTER a:
mcopy -sv binaries/os2/16bit/watcom11/fssetter.exe a:
mv fssetter.img diskimgs/os2.img

# For 32-bit OS/2 use Watcom 11
dd if=/dev/zero of=fssetter.img bs=512 count=2880 status=none
mformat -f 1440 -v FSSETTER a:
mcopy -sv binaries/os2/32bit/watcom11/fssetter.exe a:
mv fssetter.img diskimgs/os2_v2.img

# Copy images as generated by Retro68
cp binaries/macos/retro68/m68k/fssetter.dsk diskimgs/mac68k.dsk
cp binaries/macos/retro68/ppc/fssetter.dsk diskimgs/macppc.dsk

# Create image for Atari ST
dd if=/dev/zero of=fssetter.img bs=512 count=1440 status=none
mformat -f 720 -v FSSETTER a:
mcopy -sv binaries/atarist/fssetter.ttp a:
mv fssetter.img diskimgs/atarist.img

# Copy for Windows
dd if=/dev/zero of=fssetter.img bs=512 count=2880 status=none
mformat -f 1440 -v FSSETTER a:
# For x86 copy Watcom 11
mmd a:/I386
mcopy -sv binaries/win32/x86/watcom11/fssetter.exe a:/I386/fssetter.exe
# For x86_64 copy MingW
mmd a:/AMD64
mcopy -sv binaries/win32/x64/mingw/fssetter.exe a:/AMD64/fssetter.exe
# For ARM copy Visual Studio 2019
mmd a:/ARM
mcopy -sv binaries/win32/arm/msvs2019/fssetter.exe a:/ARM/fssetter.exe
# Also copy Cygwin
mmd a:/CYGWIN
mmd a:/CYGWIN/AMD64
mcopy -sv binaries/win32/x64/cygwin/fssetter.exe a:/CYGWIN/AMD64/fssetter.exe
mv fssetter.img diskimgs/win32.img

# For BeOS and Haiku
dd if=/dev/zero of=fssetter.img bs=512 count=2880 status=none
mformat -f 1440 -v FSSETTER a:
mcopy -sv binaries/beos a:
mcopy -sv binaries/haiku a:
mv fssetter.img diskimgs/beos.img
