//
// Created by claunia on 11/3/21.
//

#ifndef SETTER_SRC_WIN32_VOLUME_H_
#define SETTER_SRC_WIN32_VOLUME_H_

BOOL(WINAPI* WinGetDiskFreeSpaceExA)(LPCSTR, PULARGE_INTEGER, PULARGE_INTEGER, PULARGE_INTEGER);

#endif // SETTER_SRC_WIN32_VOLUME_H_
